type Event {
  id: ID!
  title: String!
  description: String
  code: ID
  startAt: DateTime!
  endAt: DateTime
  timetable: Timetable!
  owner: User!
  isOwner: Boolean!
  createdAt: DateTime!
  updatedAt: DateTime
  recurrence: Recurrence
}

input EditEventInput {
  id: ID
  title: NonEmptyString!
  description: NonEmptyString
  startAt: DateTime!
  endAt: DateTime
  timetableId: ID
}
