enum RepeatFrequency {
  DAILY
  WEEKLY
  MONTHLY
  YEARLY
}

type Event {
  id: ID!
  title: String!
  description: String
  startDate: Date!
  startTime: Time
  endTime: Time
  timetable: Timetable!
  owner: User!
  isOwner: Boolean!
  isCancelled: Boolean!
  cancelledDates: [Date]!
  createdAt: DateTime!
  updatedAt: DateTime
  repeat: RepeatFrequency
}

input EditEventInput {
  id: ID
  title: NonEmptyString!
  description: NonEmptyString
  startDate: Date!
  startTime: Time
  endTime: Time
  timetableId: ID
  repeat: RepeatFrequency
}
