type Event {
  id: ID!
  title: String!
  description: String
  code: ID
  startDate: Date!
  startTime: Time
  endTime: Time
  timetable: Timetable!
  owner: User!
  isOwner: Boolean!
  createdAt: DateTime!
  updatedAt: DateTime
  recurrence: Recurrence
}

input EditEventInput {
  id: ID
  title: NonEmptyString!
  description: NonEmptyString
  startDate: Date!
  startTime: Time
  endTime: Time
  timetableId: ID
}
