type Recurrence {
  freq: Frequency!
  interval: Int!
  until: Date
}

input RecurrenceInput {
  freq: Frequency!
  interval: PositiveInt!
  until: Date
}

enum Frequency {
  DAILY
  WEEKLY
  MONTHLY
  YEARLY
}
