type Timetable {
  id: ID!
  title: String!
  description: String
  events: [Event]!
  owner: User!
  isOwner: Boolean!
  createdAt: DateTime!
  updatedAt: DateTime
}

input EditTimetableInput {
  id: ID
  title: NonEmptyString!
  description: NonEmptyString
  events: [EditEventInput]!
}

type Query {
  getTimetableById(id: ID!): Timetable! @auth
}

type Mutation {
  createTimetable(input: EditTimetableInput!): Timetable! @auth
  updateTimetable(input: EditTimetableInput!): Timetable! @auth
  deleteTimetable(id: ID!, reason: NonEmptyString): Timetable! @auth
  saveTimetable(id: ID!): Timetable! @auth
  unsaveTimetable(id: ID!): Timetable! @auth
}
